main:
	g++ -o main ../../../spi.cpp ../../../file_io.cpp ../../../fpga_io.cpp ../../../user_io.cpp ../../daphne.cpp mpegscan.c vldp_internal.c vldp.c main.cpp -I. -I../ -I../../ -I../../../ -lrt --debug
clean:
	rm main
